name: Deploy ECS Infrastructure
'on':
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2

jobs:

  deploy-dev:
    name: Deploy ECS + LB Dev via Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.11

      - name: Create or Update ECS Service
        uses: dflook/terraform-apply@v1
        with:
          path: terraform/dev
          auto_approve: true
          backend_config: key=infrastructure-dev

  deploy-prod:
    name: Deploy ECS + LB Prod via Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.11

      - name: Create or Update ECS Service
        uses: dflook/terraform-apply@v1
        with:
          path: terraform/production
          auto_approve: true
          backend_config: key=infrastructure
